global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:9090', 'localhost:9100']

  - job_name: 'ec2'
    ec2_sd_configs:
      - region: ap-southeast-2
        port: 9100

    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name, __meta_ec2_availability_zone]
        target_label: instance

      - source_labels: [__meta_ec2_instance_id]
        target_label: instance_id
      
      - source_labels: [__meta_ec2_instance_type]
        target_label: instance_type
